# Generated by Django 4.2.5 on 2024-01-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
