# Generated by Django 5.0.2 on 2024-02-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_posts_id_alter_users_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
